version: "2"

services:
  alfresco-data:
    image: busybox
    volumes:
      - /home/tony/Documenti/docker-data/alfresco/postgres:/var/lib/postgresql/data
  postgres:
    image: postgres:9.4.4
    volumes_from:
      - alfresco-data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  solr6: 
    image: pdubois/solr6:latest
    environment:
      - ALFRESCO_HOST=alfresco
  alfresco:
    image: "pdubois/docker-alfresco:master"
    ports:
      - 8443:8443
    environment:
      - INITIAL_PASS=admun
      - CONTAINER_FUNCTION=tomcat
      - ALF_1=db.url.EQ.jdbc:postgresql:\/\/postgres:5432\/alfresco
      - ALF_2=db.password.EQ.mysecretpassword  
      - ALF_3=db.username.EQ.postgres
      - ALF_4=index.subsystem.name.EQ.solr6
      - ALF_5=solr.secureComms.EQ.none
      - ALF_6=solr.host.EQ.solr6
      - ALF_7=solr.port.EQ.8983
      - ALF_8=solr.port.ssl.EQ.8443
      - DB_CONTAINER_NAME=postgres
    depends_on:
      - postgres
      - solr6
