version: "2"

services:
  cassandra-data:
    image: busybox
    volumes:
      - /home/tony/Documenti/docker-data/cassandra:/var/lib/cassandra
  cassandra:
    image: cassandra:3.9
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 7199:7199
    volumes_from:
      - cassandra-data
