FROM dock0/arch

RUN pacman -Syu --noconfirm base-devel python2 nodejs npm \
&& cd /usr/local \
&& git clone git://github.com/c9/core.git c9sdk \
&& cd c9sdk \
&& ./scripts/install-sdk.sh \
&& mkdir /workspace


VOLUME /workspace
EXPOSE 8181
ENTRYPOINT ["/usr/local/c9sdk/server.js", "-w", "/workspace", "-l", "0.0.0.0", "-a"]
