elastic-data:
  image: busybox
  volumes:
    - /home/tony/docker_data/elastic:/usr/share/elasticsearch/data
elastic:
  image: elastickopf
  ports:
    - 9200:9200
    - 9300:9300
  volumes_from:
    - elastic-data
kibana:
  image: kibana
  ports:
    - 5601:5601
  links:
    - elastic
  environment:
    ELASTICSEARCH_URL: 'http://elastic:9200/'
beanstalkd:
  image: schickling/beanstalkd
  ports:
    - 11300:11300
beanstalkd-console:
  image: schickling/beanstalkd-console
  ports:
    - 2080:2080
  links:
    - beanstalkd
