elastic-data:
  image: busybox
  volumes:
    - /home/tony/docker_data/elastic:/usr/share/elasticsearch/data
elastic:
  image: elastickopf
  ports:
    - 9200:9200
    - 9300:9300
  volumes_from:
    - elastic-data
kibana:
  image: kibana
  ports:
    - 5601:5601
  links:
    - elastic
  environment:
    ELASTICSEARCH_URL: 'http://elastic:9200/'
rabbit-data:
  image: busybox
  volumes:
    - /home/tony/docker_data/rabbit:/var/lib/rabbitmq
rabbit:
  image: rabbitmq:3-management
  hostname: rabbitdevel
  ports:
    - 5672:5672
    - 15672:15672
  volumes_from:
    - rabbit-data
