sqlserver-data:
  image: busybox
  volumes:
    - /home/tony/docker_data/sqlserver:/var/opt/mssql
sqlserver:
  image: microsoft/mssql-server-linux
  ports:
    - 1433:1433
  environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=fAs0lato
  volumes_from:
    - sqlserver-data
