elastic-data:
  image: busybox
  volumes:
    - /home/tony/docker_data/elastic:/usr/share/elasticsearch/data
elastic:
  image: elastic-inquisitor
  ports:
    - 9200:9200
    - 9300:9300
  volumes_from:
    - elastic-data
kibana:
  image: kibana
  ports:
    - 5601:5601
  links:
    - elastic
  environment:
    ELASTICSEARCH_URL: 'http://elastic:9200/'
